version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rooydad_db
    restart: always
    environment:
      - POSTGRES_DB=rooydad_db
      - POSTGRES_USER=rooydad_user
      - POSTGRES_PASSWORD=rooydad_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: